### ISSUE TITLE
Twitcher unable to handle large http POST?

### ISSUE THREAD

**Issue by tlvu** [Ouranosinc/Magpie#189]
@dbyrns 

First off, sorry to hijack Magpie for Twitcher question, I was not able to find the "Issues" tab on Ouranos twitcher repo (https://github.com/Ouranosinc/twitcher).

Image: `pavics/twitcher:pavics-0.3.16`.

In this gist https://gist.github.com/tlvu/a9f63c90b6538050d3e9d432b5d276f1 (https://nbviewer.jupyter.org/gist/tlvu/a9f63c90b6538050d3e9d432b5d276f1), there is a Raven notebook that submit a rather large/gigantic POST to Raven wps through twitcher `DEBUG:urllib3.connectionpool:https://lvu.ouranos.ca:443 "POST /twitcher/ows/proxy/raven/wps HTTP/1.1" 413 199` and the resulting is `XMLSyntaxError: Opening and ending tag mismatch: hr line 5 and body, line 6, column 8`.

Bypassing twitcher and hitting the Raven wps directly works so it's twitcher that was unable to process the request.

With twitcher in front, tracing Raven, the request did not even made it to Raven.  Tracing twitcher at Debug level, there is no trace of this large/gigantic POST coming in either.

Any suggestions, debugging tips?  Is this a known issue?  Would upgrading to latest and greatest twitcher fix this issue?

Edit:

Http code 413 is indeed "Payload Too Large", see https://httpstatuses.com/413

Relevant Server Logs:
```
==> /opt/birdhouse/var/log/supervisor/nginx.log <==
2019/06/11 18:32:42 [error] 72#72: *9 client intended to send too large body: 1158967 bytes, client: 172.25.0.1, server: localhost, request: "POST /ows/proxy/raven/wps HTTP/1.0", host: "lvu.ouranos.ca"
```

**Comment by fmigneault** [comment]
Try posting it there :
https://github.com/bird-house/twitcher/issues

**Comment by tlvu** [comment]
> Try posting it there :
> https://github.com/bird-house/twitcher/issues

Since we are using Ouranos twitcher and there are much differences between Ouranos twitcher and bird-house twitcher, I felt I had to ask you guys at the CRIM who maintain Ouranos twitcher.

But sure I can post on bird-house twitcher, maybe they have some useful clues.

**Comment by dbyrns** [comment]
In fact, the 1.1.0 version almost use the stock birdhouse twitcher. @fmigneault could confirm, but by config, we can even remove the magpie hook completely. However for the 0.3.16, I agree that the difference is not trivial and the issue you are experiencing could be unrelated to birdhouse. If you are working on upgrading twitcher to the latest version, you could check against that version before posting the issue directly to the birdhouse repo.

**Comment by tlvu** [comment]
Is it possible for the CRIM to share the docker-compose.yml and all config files used for your latest twitcher/magpie combo?

In fact ... are you guys source controlling your various docker-compose.yml somewhere, can I just have access to that repo?

Don't want to spend time tracking down which config have changed/added/deleted compared to our very ancient twitcher/magpie combo.

**Comment by fmigneault** [comment]
docker-compose should be something like: 

```
  magpie:
    image: pavics/magpie:1.1.0
    container_name: magpie
    ports:
      - "2001:2001"
    environment:
      HOSTNAME: $HOST_FQDN
      FORWARDED_ALLOW_IPS: "*"
    depends_on:
      - postgres
    links:
      - postgres
    volumes:
      - ./config/magpie/permissions.cfg:/opt/local/src/magpie/config/permissions.cfg
      - ./config/magpie/providers.cfg:/opt/local/src/magpie/config/providers.cfg
      - ./config/magpie/magpie.env:/opt/local/src/magpie/magpie/env/magpie.env
      - ./config/postgres/credentials.env:/opt/local/src/magpie/magpie/env/postgres.env
    restart: always

  twitcher:
    image: pavics/twitcher:magpie-1.1.0
    container_name: twitcher
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - magpie
    links:
      - postgres
    env_file:
      - ./config/postgres/credentials.env
    volumes:
      - ./config/twitcher/twitcher.ini:/opt/birdhouse/src/twitcher/twitcher.ini
    command: 'pserve /opt/birdhouse/src/twitcher/twitcher.ini'
    restart: always
```

new file `twitcher.ini.template`, something like following: 
(variables must be written with `pavics-compose.sh`)

```
###
# app configuration
# https://docs.pylonsproject.org/projects/pyramid/en/latest/narr/environment.html
###

[app:main]
use = egg:pyramid_twitcher

pyramid.reload_templates = true
pyramid.debug_authorization = false
pyramid.debug_notfound = false
pyramid.debug_routematch = false
pyramid.default_locale_name = en
pyramid.includes =
sqlalchemy.url = postgresql://${POSTGIS_USER}:${POSTGIS_PASSWORD}@postgis:${POSTGIS_PORT}/twitcher

retry.attempts = 3

# By default, the toolbar only appears for clients from IP addresses
# '127.0.0.1' and '::1'.
# debugtoolbar.hosts = 127.0.0.1 ::1

# twitcher
twitcher.url = https://${HOST_FQDN}/twitcher
twitcher.adapter = magpie.adapter.MagpieAdapter
twitcher.rpcinterface = false
twitcher.username =
twitcher.password =
twitcher.ows_security = true
twitcher.ows_proxy = true
twitcher.ows_proxy_delegate = false
twitcher.ows_proxy_protected_path = /ows
twitcher.workdir =
twitcher.prefix =

# magpie (for twitcher.adapter)
magpie.url = https://${HOST_FQDN}/magpie
magpie.secret = ${MAGPIE_SECRET}
magpie.admin_user = ${MAGPIE_ADMIN_USER}
magpie.admin_password = ${MAGPIE_ADMIN_PW}

###
# wsgi server configuration
###

[alembic]
# path to migration scripts
script_location = twitcher/alembic
file_template = %%(year)d%%(month).2d%%(day).2d_%%(rev)s
# file_template = %%(rev)s_%%(slug)s

[server:main]
use = egg:waitress#main
listen = 0.0.0.0:8000

###
# logging configuration
# https://docs.pylonsproject.org/projects/pyramid/en/latest/narr/logging.html
###

[loggers]
keys = root, twitcher, sqlalchemy

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = INFO
handlers = console

[logger_twitcher]
level = INFO
handlers =
qualname = twitcher

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine
# "level = INFO" logs SQL queries.
# "level = DEBUG" logs SQL queries and results.
# "level = WARN" logs neither.  (Recommended for production systems.)

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(asctime)s %(levelname)-5.5s [%(name)s:%(lineno)s][%(threadName)s] %(message)s
```

Twitcher's port was changed.
It can be mapped to the old one or be updated in the nginx config files.
